/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;





/**
 *
 * @author bycha y el cerebelo de j
 */



public class Avanzado extends javax.swing.JPanel {
  private controlador.Juego controladorJuego;
      // Matriz para mapear botones
    private javax.swing.JButton[][] botonesMatriz;
    /**
     * Creates new form Principiante
     */
    
    public Avanzado() {
        initComponents();
    cargarMatrizBotones();
    this.controladorJuego = new controlador.Juego(this);
    this.controladorJuego.iniciarJuegoControlador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BtnVolver = new javax.swing.JButton();
        TxtDificultad = new javax.swing.JLabel();
        TxtPuntaje = new javax.swing.JLabel();
        TxtIntentos = new javax.swing.JLabel();
        TxtParejas = new javax.swing.JLabel();
        TxtTiempo = new javax.swing.JLabel();
        btn0_0 = new javax.swing.JButton();
        btn0_1 = new javax.swing.JButton();
        btn0_2 = new javax.swing.JButton();
        btn0_3 = new javax.swing.JButton();
        btn1_0 = new javax.swing.JButton();
        btn2_0 = new javax.swing.JButton();
        btn3_0 = new javax.swing.JButton();
        btn1_1 = new javax.swing.JButton();
        btn2_1 = new javax.swing.JButton();
        btn3_1 = new javax.swing.JButton();
        btn1_2 = new javax.swing.JButton();
        btn2_2 = new javax.swing.JButton();
        btn1_3 = new javax.swing.JButton();
        btn3_2 = new javax.swing.JButton();
        btn2_3 = new javax.swing.JButton();
        btn3_3 = new javax.swing.JButton();
        btn0_4 = new javax.swing.JButton();
        btn0_5 = new javax.swing.JButton();
        btn0_6 = new javax.swing.JButton();
        btn0_7 = new javax.swing.JButton();
        btn1_4 = new javax.swing.JButton();
        btn1_5 = new javax.swing.JButton();
        btn1_6 = new javax.swing.JButton();
        btn1_7 = new javax.swing.JButton();
        btn2_4 = new javax.swing.JButton();
        btn2_5 = new javax.swing.JButton();
        btn2_6 = new javax.swing.JButton();
        btn2_7 = new javax.swing.JButton();
        btn3_4 = new javax.swing.JButton();
        btn3_5 = new javax.swing.JButton();
        btn3_6 = new javax.swing.JButton();
        btn3_7 = new javax.swing.JButton();
        btn4_0 = new javax.swing.JButton();
        btn5_0 = new javax.swing.JButton();
        btn6_0 = new javax.swing.JButton();
        btn7_0 = new javax.swing.JButton();
        btn4_1 = new javax.swing.JButton();
        btn4_2 = new javax.swing.JButton();
        btn4_3 = new javax.swing.JButton();
        btn4_4 = new javax.swing.JButton();
        btn4_5 = new javax.swing.JButton();
        btn4_6 = new javax.swing.JButton();
        btn4_7 = new javax.swing.JButton();
        btn5_1 = new javax.swing.JButton();
        btn5_2 = new javax.swing.JButton();
        btn5_3 = new javax.swing.JButton();
        btn5_4 = new javax.swing.JButton();
        btn5_5 = new javax.swing.JButton();
        btn5_6 = new javax.swing.JButton();
        btn5_7 = new javax.swing.JButton();
        btn6_1 = new javax.swing.JButton();
        btn6_2 = new javax.swing.JButton();
        btn6_3 = new javax.swing.JButton();
        btn6_4 = new javax.swing.JButton();
        btn6_5 = new javax.swing.JButton();
        btn6_6 = new javax.swing.JButton();
        btn6_7 = new javax.swing.JButton();
        btn7_1 = new javax.swing.JButton();
        btn7_2 = new javax.swing.JButton();
        btn7_3 = new javax.swing.JButton();
        btn7_4 = new javax.swing.JButton();
        btn7_5 = new javax.swing.JButton();
        btn7_6 = new javax.swing.JButton();
        btn7_7 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(700, 460));
        setMinimumSize(new java.awt.Dimension(700, 460));
        setPreferredSize(new java.awt.Dimension(700, 460));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(700, 280));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 280));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 280));

        BtnVolver.setBackground(new java.awt.Color(255, 255, 153));
        BtnVolver.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        BtnVolver.setText("Volver");
        BtnVolver.setPreferredSize(new java.awt.Dimension(200, 80));
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        TxtDificultad.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        TxtDificultad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtDificultad.setText("AVANZADO");

        TxtPuntaje.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        TxtPuntaje.setOpaque(true);

        TxtIntentos.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        TxtIntentos.setOpaque(true);

        TxtParejas.setBackground(new java.awt.Color(255, 255, 255));
        TxtParejas.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        TxtParejas.setOpaque(true);

        TxtTiempo.setBackground(new java.awt.Color(255, 255, 255));
        TxtTiempo.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        TxtTiempo.setOpaque(true);

        btn0_0.setText("[ ? ]");
        btn0_0.setMaximumSize(new java.awt.Dimension(70, 30));
        btn0_0.setMinimumSize(new java.awt.Dimension(70, 30));
        btn0_0.setPreferredSize(new java.awt.Dimension(70, 30));
        btn0_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0_0ActionPerformed(evt);
            }
        });

        btn0_1.setText("[ ? ]");
        btn0_1.setMaximumSize(new java.awt.Dimension(70, 30));
        btn0_1.setMinimumSize(new java.awt.Dimension(70, 30));
        btn0_1.setPreferredSize(new java.awt.Dimension(70, 30));
        btn0_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0_1ActionPerformed(evt);
            }
        });

        btn0_2.setText("[ ? ]");
        btn0_2.setMaximumSize(new java.awt.Dimension(70, 30));
        btn0_2.setMinimumSize(new java.awt.Dimension(70, 30));
        btn0_2.setPreferredSize(new java.awt.Dimension(70, 30));
        btn0_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0_2ActionPerformed(evt);
            }
        });

        btn0_3.setText("[ ? ]");
        btn0_3.setMaximumSize(new java.awt.Dimension(70, 30));
        btn0_3.setMinimumSize(new java.awt.Dimension(70, 30));
        btn0_3.setPreferredSize(new java.awt.Dimension(70, 30));
        btn0_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0_3ActionPerformed(evt);
            }
        });

        btn1_0.setText("[ ? ]");
        btn1_0.setMaximumSize(new java.awt.Dimension(70, 30));
        btn1_0.setMinimumSize(new java.awt.Dimension(70, 30));
        btn1_0.setPreferredSize(new java.awt.Dimension(70, 30));
        btn1_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_0ActionPerformed(evt);
            }
        });

        btn2_0.setText("[ ? ]");
        btn2_0.setMaximumSize(new java.awt.Dimension(70, 30));
        btn2_0.setMinimumSize(new java.awt.Dimension(70, 30));
        btn2_0.setPreferredSize(new java.awt.Dimension(70, 30));
        btn2_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_0ActionPerformed(evt);
            }
        });

        btn3_0.setText("[ ? ]");
        btn3_0.setMaximumSize(new java.awt.Dimension(70, 30));
        btn3_0.setMinimumSize(new java.awt.Dimension(70, 30));
        btn3_0.setPreferredSize(new java.awt.Dimension(70, 30));
        btn3_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_0ActionPerformed(evt);
            }
        });

        btn1_1.setText("[ ? ]");
        btn1_1.setMaximumSize(new java.awt.Dimension(70, 30));
        btn1_1.setMinimumSize(new java.awt.Dimension(70, 30));
        btn1_1.setPreferredSize(new java.awt.Dimension(70, 30));
        btn1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_1ActionPerformed(evt);
            }
        });

        btn2_1.setText("[ ? ]");
        btn2_1.setMaximumSize(new java.awt.Dimension(70, 30));
        btn2_1.setMinimumSize(new java.awt.Dimension(70, 30));
        btn2_1.setPreferredSize(new java.awt.Dimension(70, 30));
        btn2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_1ActionPerformed(evt);
            }
        });

        btn3_1.setText("[ ? ]");
        btn3_1.setMaximumSize(new java.awt.Dimension(70, 30));
        btn3_1.setMinimumSize(new java.awt.Dimension(70, 30));
        btn3_1.setPreferredSize(new java.awt.Dimension(70, 30));
        btn3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_1ActionPerformed(evt);
            }
        });

        btn1_2.setText("[ ? ]");
        btn1_2.setMaximumSize(new java.awt.Dimension(70, 30));
        btn1_2.setMinimumSize(new java.awt.Dimension(70, 30));
        btn1_2.setPreferredSize(new java.awt.Dimension(70, 30));
        btn1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_2ActionPerformed(evt);
            }
        });

        btn2_2.setText("[ ? ]");
        btn2_2.setMaximumSize(new java.awt.Dimension(70, 30));
        btn2_2.setMinimumSize(new java.awt.Dimension(70, 30));
        btn2_2.setPreferredSize(new java.awt.Dimension(70, 30));
        btn2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_2ActionPerformed(evt);
            }
        });

        btn1_3.setText("[ ? ]");
        btn1_3.setMaximumSize(new java.awt.Dimension(70, 30));
        btn1_3.setMinimumSize(new java.awt.Dimension(70, 30));
        btn1_3.setPreferredSize(new java.awt.Dimension(70, 30));
        btn1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_3ActionPerformed(evt);
            }
        });

        btn3_2.setText("[ ? ]");
        btn3_2.setMaximumSize(new java.awt.Dimension(70, 30));
        btn3_2.setMinimumSize(new java.awt.Dimension(70, 30));
        btn3_2.setPreferredSize(new java.awt.Dimension(70, 30));
        btn3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_2ActionPerformed(evt);
            }
        });

        btn2_3.setText("[ ? ]");
        btn2_3.setMaximumSize(new java.awt.Dimension(70, 30));
        btn2_3.setMinimumSize(new java.awt.Dimension(70, 30));
        btn2_3.setPreferredSize(new java.awt.Dimension(70, 30));
        btn2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_3ActionPerformed(evt);
            }
        });

        btn3_3.setText("[ ? ]");
        btn3_3.setMaximumSize(new java.awt.Dimension(70, 30));
        btn3_3.setMinimumSize(new java.awt.Dimension(70, 30));
        btn3_3.setPreferredSize(new java.awt.Dimension(70, 30));
        btn3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_3ActionPerformed(evt);
            }
        });

        btn0_4.setText("[ ? ]");
        btn0_4.setMaximumSize(new java.awt.Dimension(70, 30));
        btn0_4.setMinimumSize(new java.awt.Dimension(70, 30));
        btn0_4.setPreferredSize(new java.awt.Dimension(70, 30));
        btn0_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0_4ActionPerformed(evt);
            }
        });

        btn0_5.setText("[ ? ]");
        btn0_5.setMaximumSize(new java.awt.Dimension(70, 30));
        btn0_5.setMinimumSize(new java.awt.Dimension(70, 30));
        btn0_5.setPreferredSize(new java.awt.Dimension(70, 30));
        btn0_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0_5ActionPerformed(evt);
            }
        });

        btn0_6.setText("[ ? ]");
        btn0_6.setMaximumSize(new java.awt.Dimension(70, 30));
        btn0_6.setMinimumSize(new java.awt.Dimension(70, 30));
        btn0_6.setPreferredSize(new java.awt.Dimension(70, 30));
        btn0_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0_6ActionPerformed(evt);
            }
        });

        btn0_7.setText("[ ? ]");
        btn0_7.setMaximumSize(new java.awt.Dimension(70, 30));
        btn0_7.setMinimumSize(new java.awt.Dimension(70, 30));
        btn0_7.setPreferredSize(new java.awt.Dimension(70, 30));
        btn0_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0_7ActionPerformed(evt);
            }
        });

        btn1_4.setText("[ ? ]");
        btn1_4.setMaximumSize(new java.awt.Dimension(70, 30));
        btn1_4.setMinimumSize(new java.awt.Dimension(70, 30));
        btn1_4.setPreferredSize(new java.awt.Dimension(70, 30));
        btn1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_4ActionPerformed(evt);
            }
        });

        btn1_5.setText("[ ? ]");
        btn1_5.setMaximumSize(new java.awt.Dimension(70, 30));
        btn1_5.setMinimumSize(new java.awt.Dimension(70, 30));
        btn1_5.setPreferredSize(new java.awt.Dimension(70, 30));
        btn1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_5ActionPerformed(evt);
            }
        });

        btn1_6.setText("[ ? ]");
        btn1_6.setMaximumSize(new java.awt.Dimension(70, 30));
        btn1_6.setMinimumSize(new java.awt.Dimension(70, 30));
        btn1_6.setPreferredSize(new java.awt.Dimension(70, 30));
        btn1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_6ActionPerformed(evt);
            }
        });

        btn1_7.setText("[ ? ]");
        btn1_7.setMaximumSize(new java.awt.Dimension(70, 30));
        btn1_7.setMinimumSize(new java.awt.Dimension(70, 30));
        btn1_7.setPreferredSize(new java.awt.Dimension(70, 30));
        btn1_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_7ActionPerformed(evt);
            }
        });

        btn2_4.setText("[ ? ]");
        btn2_4.setMaximumSize(new java.awt.Dimension(70, 30));
        btn2_4.setMinimumSize(new java.awt.Dimension(70, 30));
        btn2_4.setPreferredSize(new java.awt.Dimension(70, 30));
        btn2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_4ActionPerformed(evt);
            }
        });

        btn2_5.setText("[ ? ]");
        btn2_5.setMaximumSize(new java.awt.Dimension(70, 30));
        btn2_5.setMinimumSize(new java.awt.Dimension(70, 30));
        btn2_5.setPreferredSize(new java.awt.Dimension(70, 30));
        btn2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_5ActionPerformed(evt);
            }
        });

        btn2_6.setText("[ ? ]");
        btn2_6.setMaximumSize(new java.awt.Dimension(70, 30));
        btn2_6.setMinimumSize(new java.awt.Dimension(70, 30));
        btn2_6.setPreferredSize(new java.awt.Dimension(70, 30));
        btn2_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_6ActionPerformed(evt);
            }
        });

        btn2_7.setText("[ ? ]");
        btn2_7.setMaximumSize(new java.awt.Dimension(70, 30));
        btn2_7.setMinimumSize(new java.awt.Dimension(70, 30));
        btn2_7.setPreferredSize(new java.awt.Dimension(70, 30));
        btn2_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_7ActionPerformed(evt);
            }
        });

        btn3_4.setText("[ ? ]");
        btn3_4.setMaximumSize(new java.awt.Dimension(70, 30));
        btn3_4.setMinimumSize(new java.awt.Dimension(70, 30));
        btn3_4.setPreferredSize(new java.awt.Dimension(70, 30));
        btn3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_4ActionPerformed(evt);
            }
        });

        btn3_5.setText("[ ? ]");
        btn3_5.setMaximumSize(new java.awt.Dimension(70, 30));
        btn3_5.setMinimumSize(new java.awt.Dimension(70, 30));
        btn3_5.setPreferredSize(new java.awt.Dimension(70, 30));
        btn3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_5ActionPerformed(evt);
            }
        });

        btn3_6.setText("[ ? ]");
        btn3_6.setMaximumSize(new java.awt.Dimension(70, 30));
        btn3_6.setMinimumSize(new java.awt.Dimension(70, 30));
        btn3_6.setPreferredSize(new java.awt.Dimension(70, 30));
        btn3_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_6ActionPerformed(evt);
            }
        });

        btn3_7.setText("[ ? ]");
        btn3_7.setMaximumSize(new java.awt.Dimension(70, 30));
        btn3_7.setMinimumSize(new java.awt.Dimension(70, 30));
        btn3_7.setPreferredSize(new java.awt.Dimension(70, 30));
        btn3_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_7ActionPerformed(evt);
            }
        });

        btn4_0.setText("[ ? ]");
        btn4_0.setMaximumSize(new java.awt.Dimension(70, 30));
        btn4_0.setMinimumSize(new java.awt.Dimension(70, 30));
        btn4_0.setPreferredSize(new java.awt.Dimension(70, 30));
        btn4_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4_0ActionPerformed(evt);
            }
        });

        btn5_0.setText("[ ? ]");
        btn5_0.setMaximumSize(new java.awt.Dimension(70, 30));
        btn5_0.setMinimumSize(new java.awt.Dimension(70, 30));
        btn5_0.setPreferredSize(new java.awt.Dimension(70, 30));
        btn5_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5_0ActionPerformed(evt);
            }
        });

        btn6_0.setText("[ ? ]");
        btn6_0.setMaximumSize(new java.awt.Dimension(70, 30));
        btn6_0.setMinimumSize(new java.awt.Dimension(70, 30));
        btn6_0.setPreferredSize(new java.awt.Dimension(70, 30));
        btn6_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6_0ActionPerformed(evt);
            }
        });

        btn7_0.setText("[ ? ]");
        btn7_0.setMaximumSize(new java.awt.Dimension(70, 30));
        btn7_0.setMinimumSize(new java.awt.Dimension(70, 30));
        btn7_0.setPreferredSize(new java.awt.Dimension(70, 30));
        btn7_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7_0ActionPerformed(evt);
            }
        });

        btn4_1.setText("[ ? ]");
        btn4_1.setMaximumSize(new java.awt.Dimension(70, 30));
        btn4_1.setMinimumSize(new java.awt.Dimension(70, 30));
        btn4_1.setPreferredSize(new java.awt.Dimension(70, 30));
        btn4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4_1ActionPerformed(evt);
            }
        });

        btn4_2.setText("[ ? ]");
        btn4_2.setMaximumSize(new java.awt.Dimension(70, 30));
        btn4_2.setMinimumSize(new java.awt.Dimension(70, 30));
        btn4_2.setPreferredSize(new java.awt.Dimension(70, 30));
        btn4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4_2ActionPerformed(evt);
            }
        });

        btn4_3.setText("[ ? ]");
        btn4_3.setMaximumSize(new java.awt.Dimension(70, 30));
        btn4_3.setMinimumSize(new java.awt.Dimension(70, 30));
        btn4_3.setPreferredSize(new java.awt.Dimension(70, 30));
        btn4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4_3ActionPerformed(evt);
            }
        });

        btn4_4.setText("[ ? ]");
        btn4_4.setMaximumSize(new java.awt.Dimension(70, 30));
        btn4_4.setMinimumSize(new java.awt.Dimension(70, 30));
        btn4_4.setPreferredSize(new java.awt.Dimension(70, 30));
        btn4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4_4ActionPerformed(evt);
            }
        });

        btn4_5.setText("[ ? ]");
        btn4_5.setMaximumSize(new java.awt.Dimension(70, 30));
        btn4_5.setMinimumSize(new java.awt.Dimension(70, 30));
        btn4_5.setPreferredSize(new java.awt.Dimension(70, 30));
        btn4_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4_5ActionPerformed(evt);
            }
        });

        btn4_6.setText("[ ? ]");
        btn4_6.setMaximumSize(new java.awt.Dimension(70, 30));
        btn4_6.setMinimumSize(new java.awt.Dimension(70, 30));
        btn4_6.setPreferredSize(new java.awt.Dimension(70, 30));
        btn4_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4_6ActionPerformed(evt);
            }
        });

        btn4_7.setText("[ ? ]");
        btn4_7.setMaximumSize(new java.awt.Dimension(70, 30));
        btn4_7.setMinimumSize(new java.awt.Dimension(70, 30));
        btn4_7.setPreferredSize(new java.awt.Dimension(70, 30));
        btn4_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4_7ActionPerformed(evt);
            }
        });

        btn5_1.setText("[ ? ]");
        btn5_1.setMaximumSize(new java.awt.Dimension(70, 30));
        btn5_1.setMinimumSize(new java.awt.Dimension(70, 30));
        btn5_1.setPreferredSize(new java.awt.Dimension(70, 30));
        btn5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5_1ActionPerformed(evt);
            }
        });

        btn5_2.setText("[ ? ]");
        btn5_2.setMaximumSize(new java.awt.Dimension(70, 30));
        btn5_2.setMinimumSize(new java.awt.Dimension(70, 30));
        btn5_2.setPreferredSize(new java.awt.Dimension(70, 30));
        btn5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5_2ActionPerformed(evt);
            }
        });

        btn5_3.setText("[ ? ]");
        btn5_3.setMaximumSize(new java.awt.Dimension(70, 30));
        btn5_3.setMinimumSize(new java.awt.Dimension(70, 30));
        btn5_3.setPreferredSize(new java.awt.Dimension(70, 30));
        btn5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5_3ActionPerformed(evt);
            }
        });

        btn5_4.setText("[ ? ]");
        btn5_4.setMaximumSize(new java.awt.Dimension(70, 30));
        btn5_4.setMinimumSize(new java.awt.Dimension(70, 30));
        btn5_4.setPreferredSize(new java.awt.Dimension(70, 30));
        btn5_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5_4ActionPerformed(evt);
            }
        });

        btn5_5.setText("[ ? ]");
        btn5_5.setMaximumSize(new java.awt.Dimension(70, 30));
        btn5_5.setMinimumSize(new java.awt.Dimension(70, 30));
        btn5_5.setPreferredSize(new java.awt.Dimension(70, 30));
        btn5_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5_5ActionPerformed(evt);
            }
        });

        btn5_6.setText("[ ? ]");
        btn5_6.setMaximumSize(new java.awt.Dimension(70, 30));
        btn5_6.setMinimumSize(new java.awt.Dimension(70, 30));
        btn5_6.setPreferredSize(new java.awt.Dimension(70, 30));
        btn5_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5_6ActionPerformed(evt);
            }
        });

        btn5_7.setText("[ ? ]");
        btn5_7.setMaximumSize(new java.awt.Dimension(70, 30));
        btn5_7.setMinimumSize(new java.awt.Dimension(70, 30));
        btn5_7.setPreferredSize(new java.awt.Dimension(70, 30));
        btn5_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5_7ActionPerformed(evt);
            }
        });

        btn6_1.setText("[ ? ]");
        btn6_1.setMaximumSize(new java.awt.Dimension(70, 30));
        btn6_1.setMinimumSize(new java.awt.Dimension(70, 30));
        btn6_1.setPreferredSize(new java.awt.Dimension(70, 30));
        btn6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6_1ActionPerformed(evt);
            }
        });

        btn6_2.setText("[ ? ]");
        btn6_2.setMaximumSize(new java.awt.Dimension(70, 30));
        btn6_2.setMinimumSize(new java.awt.Dimension(70, 30));
        btn6_2.setPreferredSize(new java.awt.Dimension(70, 30));
        btn6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6_2ActionPerformed(evt);
            }
        });

        btn6_3.setText("[ ? ]");
        btn6_3.setMaximumSize(new java.awt.Dimension(70, 30));
        btn6_3.setMinimumSize(new java.awt.Dimension(70, 30));
        btn6_3.setPreferredSize(new java.awt.Dimension(70, 30));
        btn6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6_3ActionPerformed(evt);
            }
        });

        btn6_4.setText("[ ? ]");
        btn6_4.setMaximumSize(new java.awt.Dimension(70, 30));
        btn6_4.setMinimumSize(new java.awt.Dimension(70, 30));
        btn6_4.setPreferredSize(new java.awt.Dimension(70, 30));
        btn6_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6_4ActionPerformed(evt);
            }
        });

        btn6_5.setText("[ ? ]");
        btn6_5.setMaximumSize(new java.awt.Dimension(70, 30));
        btn6_5.setMinimumSize(new java.awt.Dimension(70, 30));
        btn6_5.setPreferredSize(new java.awt.Dimension(70, 30));
        btn6_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6_5ActionPerformed(evt);
            }
        });

        btn6_6.setText("[ ? ]");
        btn6_6.setMaximumSize(new java.awt.Dimension(70, 30));
        btn6_6.setMinimumSize(new java.awt.Dimension(70, 30));
        btn6_6.setPreferredSize(new java.awt.Dimension(70, 30));
        btn6_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6_6ActionPerformed(evt);
            }
        });

        btn6_7.setText("[ ? ]");
        btn6_7.setMaximumSize(new java.awt.Dimension(70, 30));
        btn6_7.setMinimumSize(new java.awt.Dimension(70, 30));
        btn6_7.setPreferredSize(new java.awt.Dimension(70, 30));
        btn6_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6_7ActionPerformed(evt);
            }
        });

        btn7_1.setText("[ ? ]");
        btn7_1.setMaximumSize(new java.awt.Dimension(70, 30));
        btn7_1.setMinimumSize(new java.awt.Dimension(70, 30));
        btn7_1.setPreferredSize(new java.awt.Dimension(70, 30));
        btn7_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7_1ActionPerformed(evt);
            }
        });

        btn7_2.setText("[ ? ]");
        btn7_2.setMaximumSize(new java.awt.Dimension(70, 30));
        btn7_2.setMinimumSize(new java.awt.Dimension(70, 30));
        btn7_2.setPreferredSize(new java.awt.Dimension(70, 30));
        btn7_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7_2ActionPerformed(evt);
            }
        });

        btn7_3.setText("[ ? ]");
        btn7_3.setMaximumSize(new java.awt.Dimension(70, 30));
        btn7_3.setMinimumSize(new java.awt.Dimension(70, 30));
        btn7_3.setPreferredSize(new java.awt.Dimension(70, 30));
        btn7_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7_3ActionPerformed(evt);
            }
        });

        btn7_4.setText("[ ? ]");
        btn7_4.setMaximumSize(new java.awt.Dimension(70, 30));
        btn7_4.setMinimumSize(new java.awt.Dimension(70, 30));
        btn7_4.setPreferredSize(new java.awt.Dimension(70, 30));
        btn7_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7_4ActionPerformed(evt);
            }
        });

        btn7_5.setText("[ ? ]");
        btn7_5.setMaximumSize(new java.awt.Dimension(70, 30));
        btn7_5.setMinimumSize(new java.awt.Dimension(70, 30));
        btn7_5.setPreferredSize(new java.awt.Dimension(70, 30));
        btn7_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7_5ActionPerformed(evt);
            }
        });

        btn7_6.setText("[ ? ]");
        btn7_6.setMaximumSize(new java.awt.Dimension(70, 30));
        btn7_6.setMinimumSize(new java.awt.Dimension(70, 30));
        btn7_6.setPreferredSize(new java.awt.Dimension(70, 30));
        btn7_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7_6ActionPerformed(evt);
            }
        });

        btn7_7.setText("[ ? ]");
        btn7_7.setMaximumSize(new java.awt.Dimension(70, 30));
        btn7_7.setMinimumSize(new java.awt.Dimension(70, 30));
        btn7_7.setPreferredSize(new java.awt.Dimension(70, 30));
        btn7_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7_7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtIntentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtParejas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addComponent(TxtPuntaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn1_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn1_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn1_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn1_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn2_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn3_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn0_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn0_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn0_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn0_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn0_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn0_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn0_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn0_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn4_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn4_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn4_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn4_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn4_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn4_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn4_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn4_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn5_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn6_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn7_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn7_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn7_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn7_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn7_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn7_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn7_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn7_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(TxtTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtPuntaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(TxtDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtIntentos, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(TxtParejas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn0_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn0_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn0_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn0_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn0_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn0_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn3_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn6_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
        Menu panel = new Menu();
        panel.setVisible(true);
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void btn0_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0_1ActionPerformed
    if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(0, 1);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btn0_1ActionPerformed

    private void btn0_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0_2ActionPerformed
           if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(0, 2);
    } // TODO add your handling code here:
    }//GEN-LAST:event_btn0_2ActionPerformed

    private void btn0_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0_3ActionPerformed
         if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(0, 3);
    }   // TODO add your handling code here:
    }//GEN-LAST:event_btn0_3ActionPerformed

    private void btn1_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_0ActionPerformed
          if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(1, 0);
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btn1_0ActionPerformed

    private void btn2_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_0ActionPerformed
        if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(2, 0);
    }    // TODO add your handling code here:
    }//GEN-LAST:event_btn2_0ActionPerformed

    private void btn3_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_0ActionPerformed
          if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(3, 0);
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btn3_0ActionPerformed

    private void btn1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_1ActionPerformed
         if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(1, 1);
    }   // TODO add your handling code here:
    }//GEN-LAST:event_btn1_1ActionPerformed

    private void btn2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_1ActionPerformed
         if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(2, 1);
    }   // TODO add your handling code here:
    }//GEN-LAST:event_btn2_1ActionPerformed

    private void btn3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_1ActionPerformed
          if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(3, 1);
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btn3_1ActionPerformed

    private void btn1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_2ActionPerformed
          if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(1, 2);
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btn1_2ActionPerformed

    private void btn2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_2ActionPerformed
           if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(2, 2);
    } // TODO add your handling code here:
    }//GEN-LAST:event_btn2_2ActionPerformed

    private void btn1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_3ActionPerformed
         if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(1, 3);
    }   // TODO add your handling code here:
    }//GEN-LAST:event_btn1_3ActionPerformed

    private void btn3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_2ActionPerformed
           if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(3, 2);
    } // TODO add your handling code here:
    }//GEN-LAST:event_btn3_2ActionPerformed

    private void btn2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_3ActionPerformed
          if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(2, 3);
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btn2_3ActionPerformed

    private void btn3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_3ActionPerformed
          if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(3, 3);
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btn3_3ActionPerformed

    private void btn0_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0_0ActionPerformed
    if (controladorJuego != null) {
        controladorJuego.seleccionarCartaControlador(0, 0);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btn0_0ActionPerformed

    private void btn0_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0_4ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(0, 4);
    }//GEN-LAST:event_btn0_4ActionPerformed

    private void btn0_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0_5ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(0, 5);
    }//GEN-LAST:event_btn0_5ActionPerformed

    private void btn0_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0_6ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(0, 6);
    }//GEN-LAST:event_btn0_6ActionPerformed

    private void btn0_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0_7ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(0, 7);
    }//GEN-LAST:event_btn0_7ActionPerformed

    private void btn1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_4ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(1, 4);
    }//GEN-LAST:event_btn1_4ActionPerformed

    private void btn1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_5ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(1, 5);
    }//GEN-LAST:event_btn1_5ActionPerformed

    private void btn1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_6ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(1, 6);
    }//GEN-LAST:event_btn1_6ActionPerformed

    private void btn1_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_7ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(1, 7);
    }//GEN-LAST:event_btn1_7ActionPerformed

    private void btn2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_4ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(2, 4);
    }//GEN-LAST:event_btn2_4ActionPerformed

    private void btn2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_5ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(2, 5);
    }//GEN-LAST:event_btn2_5ActionPerformed

    private void btn2_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_6ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(2, 6);
    }//GEN-LAST:event_btn2_6ActionPerformed

    private void btn2_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_7ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(2, 7);
    }//GEN-LAST:event_btn2_7ActionPerformed

    private void btn3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_4ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(3, 4);
    }//GEN-LAST:event_btn3_4ActionPerformed

    private void btn3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_5ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(3, 5);
    }//GEN-LAST:event_btn3_5ActionPerformed

    private void btn3_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_6ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(3, 6);
    }//GEN-LAST:event_btn3_6ActionPerformed

    private void btn3_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_7ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(3, 7);
    }//GEN-LAST:event_btn3_7ActionPerformed

    private void btn4_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4_0ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(4, 0);
    }//GEN-LAST:event_btn4_0ActionPerformed

    private void btn5_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5_0ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(5, 0);
    }//GEN-LAST:event_btn5_0ActionPerformed

    private void btn6_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6_0ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(6, 0);
    }//GEN-LAST:event_btn6_0ActionPerformed

    private void btn7_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7_0ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(7, 0);
    }//GEN-LAST:event_btn7_0ActionPerformed

    private void btn4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4_1ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(4, 1);
    }//GEN-LAST:event_btn4_1ActionPerformed

    private void btn4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4_2ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(4, 2);
    }//GEN-LAST:event_btn4_2ActionPerformed

    private void btn4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4_3ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(4, 3);
    }//GEN-LAST:event_btn4_3ActionPerformed

    private void btn4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4_4ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(4, 4);
    }//GEN-LAST:event_btn4_4ActionPerformed

    private void btn4_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4_5ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(4, 5);
    }//GEN-LAST:event_btn4_5ActionPerformed

    private void btn4_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4_6ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(4, 6);
    }//GEN-LAST:event_btn4_6ActionPerformed

    private void btn4_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4_7ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(4, 7);
    }//GEN-LAST:event_btn4_7ActionPerformed

    private void btn5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5_1ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(5, 1);
    }//GEN-LAST:event_btn5_1ActionPerformed

    private void btn5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5_2ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(5, 2);
    }//GEN-LAST:event_btn5_2ActionPerformed

    private void btn5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5_3ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(5, 3);
    }//GEN-LAST:event_btn5_3ActionPerformed

    private void btn5_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5_4ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(5, 4);
    }//GEN-LAST:event_btn5_4ActionPerformed

    private void btn5_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5_5ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(5, 5);
    }//GEN-LAST:event_btn5_5ActionPerformed

    private void btn5_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5_6ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(5, 6);
    }//GEN-LAST:event_btn5_6ActionPerformed

    private void btn5_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5_7ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(5, 7);
    }//GEN-LAST:event_btn5_7ActionPerformed

    private void btn6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6_1ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(6, 1);
    }//GEN-LAST:event_btn6_1ActionPerformed

    private void btn6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6_2ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(6, 2);
    }//GEN-LAST:event_btn6_2ActionPerformed

    private void btn6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6_3ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(6, 3);
    }//GEN-LAST:event_btn6_3ActionPerformed

    private void btn6_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6_4ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(6, 4);
    }//GEN-LAST:event_btn6_4ActionPerformed

    private void btn6_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6_5ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(6, 5);
    }//GEN-LAST:event_btn6_5ActionPerformed

    private void btn6_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6_6ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(6, 6);
    }//GEN-LAST:event_btn6_6ActionPerformed

    private void btn6_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6_7ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(6, 7);
    }//GEN-LAST:event_btn6_7ActionPerformed

    private void btn7_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7_1ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(7, 1);
    }//GEN-LAST:event_btn7_1ActionPerformed

    private void btn7_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7_2ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(7, 2);
    }//GEN-LAST:event_btn7_2ActionPerformed

    private void btn7_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7_3ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(7, 3);
    }//GEN-LAST:event_btn7_3ActionPerformed

    private void btn7_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7_4ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(7, 4);
    }//GEN-LAST:event_btn7_4ActionPerformed

    private void btn7_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7_5ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(7, 5);
    }//GEN-LAST:event_btn7_5ActionPerformed

    private void btn7_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7_6ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(7, 6);
    }//GEN-LAST:event_btn7_6ActionPerformed

    private void btn7_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7_7ActionPerformed
        if (controladorJuego != null) controladorJuego.seleccionarCartaControlador(7, 7);
    }//GEN-LAST:event_btn7_7ActionPerformed
public void IniciarCronometro(boolean activo){
  
      
}
    private void cargarMatrizBotones() {
        botonesMatriz = new javax.swing.JButton[8][8];
        
        // Fila 0
        botonesMatriz[0][0] = btn0_0;
        botonesMatriz[0][1] = btn0_1;
        botonesMatriz[0][2] = btn0_2;
        botonesMatriz[0][3] = btn0_3;
        botonesMatriz[0][4] = btn0_4;
        botonesMatriz[0][5] = btn0_5;
        botonesMatriz[0][6] = btn0_6;
        botonesMatriz[0][7] = btn0_7;
        // Fila 1
        botonesMatriz[1][0] = btn1_0;
        botonesMatriz[1][1] = btn1_1;
        botonesMatriz[1][2] = btn1_2;
        botonesMatriz[1][3] = btn1_3;
        botonesMatriz[1][4] = btn1_4;
        botonesMatriz[1][5] = btn1_5;
        botonesMatriz[1][6] = btn1_6;
        botonesMatriz[1][7] = btn1_7;
        // Fila 2
        botonesMatriz[2][0] = btn2_0;
        botonesMatriz[2][1] = btn2_1;
        botonesMatriz[2][2] = btn2_2;
        botonesMatriz[2][3] = btn2_3;
        botonesMatriz[2][4] = btn2_4;
        botonesMatriz[2][5] = btn2_5;
        botonesMatriz[2][6] = btn2_6;
        botonesMatriz[2][7] = btn2_7;
        // Fila 3
        botonesMatriz[3][0] = btn3_0;
        botonesMatriz[3][1] = btn3_1;
        botonesMatriz[3][2] = btn3_2;
        botonesMatriz[3][3] = btn3_3;
        botonesMatriz[3][4] = btn3_4;
        botonesMatriz[3][5] = btn3_5;
        botonesMatriz[3][6] = btn3_6;
        botonesMatriz[3][7] = btn3_7;
        // Fila 4
        botonesMatriz[4][0] = btn4_0;
        botonesMatriz[4][1] = btn4_1;
        botonesMatriz[4][2] = btn4_2;
        botonesMatriz[4][3] = btn4_3;
        botonesMatriz[4][4] = btn4_4;
        botonesMatriz[4][5] = btn4_5;
        botonesMatriz[4][6] = btn4_6;
        botonesMatriz[4][7] = btn4_7;
        // Fila 5
        botonesMatriz[5][0] = btn5_0;
        botonesMatriz[5][1] = btn5_1;
        botonesMatriz[5][2] = btn5_2;
        botonesMatriz[5][3] = btn5_3;
        botonesMatriz[5][4] = btn5_4;
        botonesMatriz[5][5] = btn5_5;
        botonesMatriz[5][6] = btn5_6;
        botonesMatriz[5][7] = btn5_7;
        // Fila 6
        botonesMatriz[6][0] = btn6_0;
        botonesMatriz[6][1] = btn6_1;
        botonesMatriz[6][2] = btn6_2;
        botonesMatriz[6][3] = btn6_3;
        botonesMatriz[6][4] = btn6_4;
        botonesMatriz[6][5] = btn6_5;
        botonesMatriz[6][6] = btn6_6;
        botonesMatriz[6][7] = btn6_7;
        // Fila 7
        botonesMatriz[7][0] = btn7_0;
        botonesMatriz[7][1] = btn7_1;
        botonesMatriz[7][2] = btn7_2;
        botonesMatriz[7][3] = btn7_3;
        botonesMatriz[7][4] = btn7_4;
        botonesMatriz[7][5] = btn7_5;
        botonesMatriz[7][6] = btn7_6;
        botonesMatriz[7][7] = btn7_7;
    }
        //actualiza la visualisacion del boton...duhh
    public void actualizarBotonVista(int fila, int col, String texto, boolean deshabilitado) {
        if (botonesMatriz != null && fila >= 0 && fila < 8 && col >= 0 && col < 8) {
            javax.swing.JButton btn = botonesMatriz[fila][col];
            
            if (texto.equals("[ ? ]")) {
                btn.setIcon(null);
                btn.setText("[ ? ]");
            } else {
                javax.swing.ImageIcon icono = new javax.swing.ImageIcon("src/recursos/iconos/" + texto + ".png");
                java.awt.Image img = icono.getImage().getScaledInstance(btn.getWidth(), btn.getHeight(), java.awt.Image.SCALE_SMOOTH);
                btn.setIcon(new javax.swing.ImageIcon(img));
                btn.setText("");
            }
            btn.setEnabled(!deshabilitado);
        }
    }

    public void actualizarTextoTiempoVista(String tiempoTexto) {
        this.TxtTiempo.setText(tiempoTexto);
    }
    
    public void mostrarVictoriaVista() {
        this.TxtDificultad.setText("¡Victoria!");
    }
    public void actualizarInformacionVista(int puntaje, int intentos, int parejasEncontradas, int totalParejas) { 
      if (TxtPuntaje != null) TxtPuntaje.setText("Puntos: " + puntaje);
      if (TxtIntentos != null) TxtIntentos.setText("Intentos: " + intentos);
      if (TxtParejas != null) TxtParejas.setText("Parejas: " + parejasEncontradas + "/" + totalParejas);
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel TxtDificultad;
    private javax.swing.JLabel TxtIntentos;
    private javax.swing.JLabel TxtParejas;
    private javax.swing.JLabel TxtPuntaje;
    private javax.swing.JLabel TxtTiempo;
    private javax.swing.JButton btn0_0;
    private javax.swing.JButton btn0_1;
    private javax.swing.JButton btn0_2;
    private javax.swing.JButton btn0_3;
    private javax.swing.JButton btn0_4;
    private javax.swing.JButton btn0_5;
    private javax.swing.JButton btn0_6;
    private javax.swing.JButton btn0_7;
    private javax.swing.JButton btn1_0;
    private javax.swing.JButton btn1_1;
    private javax.swing.JButton btn1_2;
    private javax.swing.JButton btn1_3;
    private javax.swing.JButton btn1_4;
    private javax.swing.JButton btn1_5;
    private javax.swing.JButton btn1_6;
    private javax.swing.JButton btn1_7;
    private javax.swing.JButton btn2_0;
    private javax.swing.JButton btn2_1;
    private javax.swing.JButton btn2_2;
    private javax.swing.JButton btn2_3;
    private javax.swing.JButton btn2_4;
    private javax.swing.JButton btn2_5;
    private javax.swing.JButton btn2_6;
    private javax.swing.JButton btn2_7;
    private javax.swing.JButton btn3_0;
    private javax.swing.JButton btn3_1;
    private javax.swing.JButton btn3_2;
    private javax.swing.JButton btn3_3;
    private javax.swing.JButton btn3_4;
    private javax.swing.JButton btn3_5;
    private javax.swing.JButton btn3_6;
    private javax.swing.JButton btn3_7;
    private javax.swing.JButton btn4_0;
    private javax.swing.JButton btn4_1;
    private javax.swing.JButton btn4_2;
    private javax.swing.JButton btn4_3;
    private javax.swing.JButton btn4_4;
    private javax.swing.JButton btn4_5;
    private javax.swing.JButton btn4_6;
    private javax.swing.JButton btn4_7;
    private javax.swing.JButton btn5_0;
    private javax.swing.JButton btn5_1;
    private javax.swing.JButton btn5_2;
    private javax.swing.JButton btn5_3;
    private javax.swing.JButton btn5_4;
    private javax.swing.JButton btn5_5;
    private javax.swing.JButton btn5_6;
    private javax.swing.JButton btn5_7;
    private javax.swing.JButton btn6_0;
    private javax.swing.JButton btn6_1;
    private javax.swing.JButton btn6_2;
    private javax.swing.JButton btn6_3;
    private javax.swing.JButton btn6_4;
    private javax.swing.JButton btn6_5;
    private javax.swing.JButton btn6_6;
    private javax.swing.JButton btn6_7;
    private javax.swing.JButton btn7_0;
    private javax.swing.JButton btn7_1;
    private javax.swing.JButton btn7_2;
    private javax.swing.JButton btn7_3;
    private javax.swing.JButton btn7_4;
    private javax.swing.JButton btn7_5;
    private javax.swing.JButton btn7_6;
    private javax.swing.JButton btn7_7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
